# Generated by Django 3.0.3 on 2020-02-05 19:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Cust_iD', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(10)])),
                ('Email', models.CharField(max_length=255)),
                ('First_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('POnumber', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(10)])),
                ('Order_date', models.IntegerField(null=True, validators=[django.core.validators.MaxLengthValidator(20)])),
                ('Cancel_date', models.IntegerField(null=True, validators=[django.core.validators.MaxLengthValidator(20)])),
                ('Ship_date', models.IntegerField(null=True, validators=[django.core.validators.MaxLengthValidator(20)])),
                ('Status', models.TextField()),
                ('Total_payment', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Cust_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test001.Customer')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('Product_ID', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(10)])),
                ('Product_type', models.TextField()),
                ('Product_name', models.TextField()),
                ('Product_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('DisplayImage', models.CharField(max_length=255)),
                ('Brand', models.TextField()),
                ('ISBN', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(13)])),
                ('Authors', models.CharField(max_length=255)),
                ('Publisher', models.CharField(max_length=255)),
                ('Release_date', models.TextField()),
                ('Num_of_pages', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(10)])),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Shopping_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(5)])),
                ('Cust_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test001.Customer')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test001.Products')),
            ],
            options={
                'db_table': 'Shopping_cart',
                'unique_together': {('Cust_ID', 'Product_ID')},
            },
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Quantity', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(5)])),
                ('POnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test001.Order')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test001.Products')),
            ],
            options={
                'db_table': 'Order_Items',
                'unique_together': {('POnumber', 'Product_ID')},
            },
        ),
        migrations.CreateModel(
            name='DetailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img_ID', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(1)])),
                ('Img_URL', models.CharField(max_length=255)),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test001.Products')),
            ],
            options={
                'db_table': 'DetailImage',
                'unique_together': {('Product_ID', 'Img_ID')},
            },
        ),
    ]
