# Generated by Django 3.0.3 on 2020-02-18 09:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test001', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Password',
        ),
        migrations.AlterField(
            model_name='customer',
            name='Cust_iD',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detailimage',
            name='Img_ID',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='Cancel_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='POnumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ship_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='Quantity',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='products',
            name='ISBN',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
        migrations.AlterField(
            model_name='products',
            name='Num_of_pages',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='Release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='Quantity',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
