# Generated by Django 3.0.3 on 2020-02-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0002_auto_20200218_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Release_date',
            field=models.DateTimeField(),
        ),
    ]
