# Generated by Django 3.0.3 on 2020-02-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0004_auto_20200219_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Cancel_by',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
