# Generated by Django 3.0.3 on 2020-03-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0005_order_cancel_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_date',
            field=models.DateTimeField(null=True),
        ),
    ]
